server:
  port: 9090

spring:
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: ${POSTGRES_CONNECTION_POOL}

    url: ${POSTGRES_CONNECT_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: ${POSTGRES_AUTO_DDL}
